name: Payment System CD

on:
  push:
    branches:
      - main
      - saga-implementation

  pull_request:
    branches:
      - main

jobs:
  validate-kubernetes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Kubernetes manifests
        run: |
          echo "Checking Kubernetes manifest files..."
          test -f k8s/config.yaml
          test -f k8s/kafka.yaml
          test -f k8s/postgres.yaml
          test -f k8s/redis.yaml
          test -f k8s/zookeeper.yaml
          test -f k8s/order-deployment.yaml
          test -f k8s/payment-deployment.yaml
          test -f k8s/notification-deployment.yaml
          echo "All Kubernetes manifest files are present."

      - name: Check Docker Hub images
        run: |
          grep -R "bobby0307/order-service:" k8s/
          grep -R "bobby0307/payment-service:" k8s/
          grep -R "bobby0307/notification-service:" k8s/
          echo "Docker Hub image references found."